name: Docker Hub CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Ensure that DOCKER_USERNAME and DOCKER_PASSWORD are set in your repository's GitHub Secrets:
          # Go to your repository on GitHub -> Settings -> Secrets and variables -> Actions -> New repository secret
          # Add DOCKER_USERNAME and DOCKER_PASSWORD with appropriate values.

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/go-web-app:${{ github.sha }} .
          docker tag $DOCKER_USERNAME/go-web-app:${{ github.sha }} $DOCKER_USERNAME/go-web-app:latest
          docker push $DOCKER_USERNAME/go-web-app:${{ github.sha }}
          docker push $DOCKER_USERNAME/go-web-app:latest