# Workflow Name: Docker Hub CI/CD
# Description: Builds, tests, and pushes a Go application's Docker image to Docker Hub on push or pull request to the master branch.
name: Docker-CI-CD

# Triggers: Run on push or pull request to master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs: Define the CI pipeline
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for versioning if needed

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Match your Go version
          cache: true # Cache Go modules for faster builds

      # Step 3: Install Go dependencies
      - name: Install Dependencies
        run: go mod download

      # Step 4: Run unit tests
      - name: Run Tests
        run: go test -v ./... # Verbose output for debugging

      # Step 5: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Note: Set DOCKER_USERNAME and DOCKER_PASSWORD in Repository Settings > Secrets and variables > Actions

      # Step 6: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/go-web-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/go-web-app:latest